services:
  webapp:
    image: harbor.tawksic.com/h-webapp/autoscale-api
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins:
    image: harbor.tawksic.com/h-webapp/jenkins
    network_mode: host
