apiVersion: apps/v1
kind: Deployment
metadata:
  name: coral
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coral
  template:
    metadata:
      labels:
        app: coral
    spec:
      containers:
      - name: coral
        image: harbor.tawksic.com/coral/api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: coral-harbor-secret
