# TODO: using minikube for now (only allows 1 node), migrate to rke2 later

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aa-k8s
  labels:
    app: aa-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aa-k8s
  template:
    metadata:
      labels:
        app: aa-k8s
    spec:
      containers:
      - image: harbor.tawksic.com/h-webapp/autoscale-api
        name: autoscale-api
        imagePullPolicy: Always
      imagePullSecrets:
      - name: harbor-secret
